Repository davidsaulrodriguez/shop-portal, pull requests merged in 2021-04, with the labels that each got.

#20 adding addressModel schema to project scope
  models/addressModel.js
Labels: type: feature, work: obvious

#22 adding merchantModel to the scope of this project
  models/merchantModel.js
Labels: type: feature, work: obvious

#18 adding categoryModel to this project scope
  models/categoryModel.js
Labels: type: feature, work: obvious

#17 adding orderModel schema to project scope
  models/orderModel.js
Labels: type: feature, work: obvious

#16 adding brandModel schema to project
  models/brandModel.js
Labels: type: feature, work: obvious

#15 Backend product schema
  models/productModel.js
Labels: type: feature, work: obvious

#14 created the backend user schema
  models/userModel.js
Labels: type: feature, work: obvious

#26 fix schema bug
  models/categoryModel.js
Labels: effort: 1, type: fix

#21 UI: Navigation Bar and React Router
  client/src/App.js
  client/src/App.jsx
  client/src/components/Navigation/Navigation.jsx
  client/src/components/Navigation/styles.jsx
  client/src/components/NavigationDrawer/NavigationDrawer.jsx
  client/src/components/NavigationDrawer/styles.jsx
  client/src/index.js
  package-lock.json
  package.json
Labels: type: feature, work: obvious

#39 WIP UI contactpage
  client/src/App.jsx
  client/src/pages/ContactUs/ContactUs.jsx
  client/src/pages/ContactUs/styles.jsx
Labels: type: feature

#38 Sign up page
  client/src/App.jsx
  client/src/pages/SignIn/SignIn.jsx
  client/src/pages/SignUp/SignUp.jsx
  client/src/pages/SignUp/styles.jsx
Labels: type: discussion, type: epic, type: feature, work: obvious

#47 updating the comments on the contact api file and package.json file for formatting prettier
  package.json
  routes/api/contact.js
Labels: work: obvious

#55 adding new feature isReviewed
  controllers/isReviewedController.js
  models/index.js
  models/isReviewedModel.js
  models/productModel.js
  routes/api/index.js
  routes/api/isReviewed.js
  routes/api/stripe.js
  scripts/brandSeed.js
  scripts/categorySeed.js
  scripts/productSeed.js
  scripts/userSeed.js
Labels: priority: soon, type: discussion, type: feature, type: feature request, work: obvious

#53 created new feature for featuring products, orders, and category
  models/brandModel.js
  models/categoryModel.js
  models/productModel.js
Labels: type: feature, type: feature request, work: obvious

#59 changing isReviewd from boolean to reference Review (hotfix)
  models/productModel.js
Labels: priority: now, type: fix, work: obvious

#49 WIP adding shop page with mock data
  client/src/App.jsx
  client/src/__mock__/ProductsList.js
  client/src/pages/Shop/Shop.jsx
  client/src/pages/Shop/styles.js
  package-lock.json
  package.json
Labels: effort: 2

#66 New feature: Stripe code
  client/public/index.html
  client/src/App.jsx
  client/src/components/CheckoutForm/index.jsx
  client/src/pages/CheckOut/CheckOut.jsx
  controllers/paymentController.js
  package-lock.json
  package.json
  routes/api/index.js
  routes/api/payment.js
  scripts/brandSeed.js
  scripts/categorySeed.js
  scripts/productSeed.js
  scripts/userSeed.js
Labels: effort: 3, work: complex

#63 Backend api route and controller new feature request for isFeatured
  controllers/productController.js
  routes/api/product.js
Labels: priority: now, type: feature request, work: complex

#70 Backend controller fix
  controllers/addressController.js
  controllers/brandController.js
  controllers/cartController.js
  controllers/categoryController.js
  controllers/contactController.js
  controllers/isReviewedController.js
  controllers/merchantController.js
  controllers/orderController.js
  controllers/productController.js
  controllers/usersController.js
  models/isReviewedModel.js
  models/productModel.js
  package-lock.json
  package.json
  routes/api/address.js
  routes/api/isReviewed.js
  routes/api/product.js
  scripts/productSeed.js
  scripts/reviewSeed.js
Labels: priority: now, type: bug, type: fix, work: obvious

#71 Fix product controller for frontend and edit seeds
  controllers/productController.js
  models/isReviewedModel.js
  models/productModel.js
  package.json
  scripts/productSeed.js
  scripts/reviewSeed.js
Labels: priority: now, type: fix, work: obvious

#72 Backend cart api fixes
  controllers/cartController.js
  models/cartModel.js
  routes/api/cart.js
  scripts/cartSeed.js
Labels: effort: 1, priority: now, type: feature, type: fix

#74 Backend cart configuration adjustments
  controllers/cartController.js
  models/cartModel.js
  routes/api/cart.js
  scripts/cartSeed.js
Labels: priority: now, type: fix, work: obvious

#75 Backend newroutes
  controllers/productController.js
  routes/api/product.js
Labels: effort: 1, priority: now, work: obvious

#76 Backend order model - fix create order feature
  controllers/orderController.js
Labels: priority: now, type: fix, work: obvious

#77 Backend is review product fix
  models/isReviewedModel.js
Labels: priority: now, type: fix, work: obvious

#69 WIP UI cartpage
  .babelrc.json
  client/.babelrc.json
  client/package-lock.json
  client/package.json
  client/src/App.jsx
  client/src/components/Quantity/Quantity.jsx
  client/src/components/Quantity/styles.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Cart/images/exampleimage.png
  client/src/pages/Cart/styles.jsx
  controllers/cartController.js
  exampleimage.png
  models/cartModel.js
  package-lock.json
  package.json
  routes/api/cart.js
  scripts/cartSeed.js
Labels: type: feature

#79 Finished itemDetails page and Cart page
  client/package-lock.json
  client/package.json
  client/public/static/images/cards/backpack.jpg
  client/src/App.jsx
  client/src/components/AverageRating/AverageRating.jsx
  client/src/components/ReviewModal/ReviewModal.jsx
  client/src/components/ReviewModal/styles.jsx
  client/src/components/UserRating/UserRating.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/Cart/images/exampleimage.png
  client/src/pages/Cart/styles.jsx
  client/src/pages/ItemDetailsPage/ItemDetailsPage.jsx
  client/src/pages/ItemDetailsPage/styles.jsx
  client/src/pages/SignIn/styles.jsx
  controllers/cartController.js
  controllers/isReviewedController.js
  controllers/productController.js
  models/cartModel.js
  package-lock.json
  package.json
  scripts/productSeed.js
  scripts/reviewSeed.js
Labels: effort: 2, priority: now, work: obvious

#80 Link 3 pages together
  client/public/manifest.json
  client/src/__mock__/ProductsList.js
  client/src/components/ReviewModal/ReviewModal.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/ItemDetailsPage/ItemDetailsPage.jsx
  client/src/pages/Shop/Shop.jsx
  controllers/cartController.js
  package.json
  scripts/cartSeed.js
  scripts/reviewSeed.js
Labels: effort: 1

#82 updated server.js
  server.js
Labels: priority: now, type: fix, work: obvious

#84 Fix itemDetails page functionality and fix remove button bug in Cart page
  client/src/components/Loading/Loading.jsx
  client/src/components/Loading/styles.jsx
  client/src/components/Quantity/Quantity.jsx
  client/src/components/Quantity/styles.jsx
  client/src/components/ReviewModal/ReviewModal.jsx
  client/src/pages/Cart/Cart.jsx
  client/src/pages/ItemDetailsPage/ItemDetailsPage.jsx
  controllers/cartController.js
  controllers/isReviewedController.js
  controllers/productController.js
  controllers/reviewController.js
  models/index.js
  models/productModel.js
  models/reviewModel.js
  routes/api/cart.js
  routes/api/index.js
  routes/api/isReviewed.js
  routes/api/product.js
  routes/api/review.js
  scripts/cartSeed.js
  scripts/productSeed.js
  scripts/reviewSeed.js
Labels: effort: 2, priority: now, type: fix, work: complicated
